### ISSUE TITLE
Create an installable binary

### ISSUE THREAD

**Issue by sscotth** [JK3Y/asepsis#4]

**Comment by JK3Y** [comment]
Unfortunately this is out of my skillset. You're more than welcome to file a PR and i'd be happy to review it. You may be able to build an installable binary via XCode.

**Comment by godfat** [comment]
@JK3Y What do you think if you just zip a binary tarball? Will that work?

I just realized that I need to install the whole Xcode, which is ~6G, and I'll need to go over through the app store which I've never used and would like to avoid if possible.

Or is it possible to just make it work with [CommandLineTools](https://developer.apple.com/download/more/?=command%20line%20tools)?

I am asking this because running `xcodebuild` will give me:

```
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
```

And I don't know what's the difference between an actual Xcode and CommandLineTools. I can compile stuffs with CommandLineTools anyway.
